[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:gunicorn]
command=gunicorn --bind 127.0.0.1:5000 --workers 2 --timeout 120 wsgi:app
directory=/api
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
